eureka:
  instance:
    lease-expiration-duration-in-seconds: 90  # 续约到期时间（默认90秒）
    lease-renewal-interval-in-seconds: 30 # 续约更新时间间隔（默认30秒）
    #appname: helloworld #定义服务名称，必须是唯一
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi
  cloud:
      config:
        label: master
        profile: dev
        uri: http://localhost:8888
