spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/snowx1985/springcloud
          search-paths: config
          username:
          password:
      label: master
  application:
    name: config-server
server:
  port: 8888
